#!/usr/bin/env node
// Convert every rotation in the vendored PVME guide corpus to RM + RSA + PVME and
// drop the files under samples/ so they can be imported and tried directly.
//
//   node scripts/make-samples.mjs [--to rm,rsa,pvme] [--only <substring>]
//
// samples/ is git-ignored — regenerate any time with `npm run samples`.

import { mkdir, rm, writeFile } from "node:fs/promises";
import { readdirSync, statSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { convertGuide, loadCatalog } from "../dist/core/index.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const corpus = path.join(root, "test", "corpus", "pvme-guides");
const outRoot = path.join(root, "samples");

const args = process.argv.slice(2);
const only = args.includes("--only") ? args[args.indexOf("--only") + 1] : null;
const formats = (args.includes("--to") ? args[args.indexOf("--to") + 1] : "rm,rsa,pvme").split(",");

const walk = (d) =>
    readdirSync(d).flatMap((f) => {
        const p = path.join(d, f);
        return statSync(p).isDirectory() ? walk(p) : p.endsWith(".txt") ? [p] : [];
    });

const safe = (s) => s.replace(/[^\w .()—-]+/g, " ").replace(/\s+/g, " ").trim().slice(0, 120);
const ext = (fmt) => (fmt === "pvme" ? "txt" : "json");

async function main() {
    const catalog = loadCatalog();
    await rm(outRoot, { recursive: true, force: true });
    await mkdir(outRoot, { recursive: true });

    let files = walk(corpus);
    if (only) files = files.filter((f) => f.toLowerCase().includes(only.toLowerCase()));

    const index = ["# Sample rotations", "", "Generated by `npm run samples` from the vendored PVME guide corpus.", ""];
    let rotationCount = 0;
    const withEstimates = new Set();
    const withUnresolved = [];

    for (const file of files) {
        const rel = path.relative(corpus, file).replace(/\\/g, "/");
        const stem = rel.replace(/\.txt$/, "");
        const text = readFileSync(file, "utf8");

        // one convert per format
        const byFormat = {};
        for (const fmt of formats) {
            try {
                byFormat[fmt] = convertGuide(text, { to: fmt, catalog });
            } catch (e) {
                console.error(`skip ${rel} (${fmt}): ${e.message}`);
            }
        }
        const any = byFormat[formats[0]];
        if (!any || any.rotations.length === 0) continue;

        const dir = path.join(outRoot, stem);
        await mkdir(dir, { recursive: true });
        index.push(`## ${stem}`);

        any.rotations.forEach((_, i) => {
            const name = any.rotations[i].name;
            rotationCount++;
            const notes = [];
            for (const fmt of formats) {
                const r = byFormat[fmt]?.rotations[i];
                if (!r) continue;
                const body = typeof r.output === "string" ? r.output : JSON.stringify(r.output, null, 2) + "\n";
                writeFile(path.join(dir, `${safe(name)} - (${fmt.toUpperCase()}).${ext(fmt)}`), body);
                const u = r.report.entries.filter((e) => e.code === "unresolved");
                const est = r.report.entries.some((e) => e.code === "estimated-timing");
                if (u.length) { notes.push(`${fmt}: ${u.length} unresolved`); withUnresolved.push(`${stem} :: ${name}`); }
                if (est) withEstimates.add(`${stem} :: ${name}`);
            }
            index.push(`- **${name}** — ${any.rotations[i].sectionPath.join(" › ")}${notes.length ? `  _(${notes.join("; ")})_` : ""}`);
        });
        index.push("");
    }

    index.push(
        "---",
        "",
        `${rotationCount} rotations from ${files.length} guides.`,
        `${withEstimates.size} use estimated RM→RSA tick timing (see each file's conversion — RM/PVME carry no absolute ticks).`,
        withUnresolved.length ? `${withUnresolved.length} have unresolved tokens.` : "All abilities resolved.",
    );
    await writeFile(path.join(outRoot, "INDEX.md"), index.join("\n") + "\n");
    console.log(`\nwrote ${rotationCount} rotations x ${formats.length} format(s) to samples/`);
    console.log(`see samples/INDEX.md`);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
